# Generated by Django 2.2.8 on 2019-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0008_auto_20191126_2306"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataqualitytask",
            options={},
        ),
        migrations.AlterModelOptions(
            name="datasetetltaskresult",
            options={},
        ),
        migrations.AddField(
            model_name="dataqualitytask",
            name="completed",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Datetime field when the task was completed in UTC",
                verbose_name="Completed DateTime",
            ),
        ),
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="completed",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Datetime field when the task was completed in UTC",
                verbose_name="Completed DateTime",
            ),
        ),
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DANGEROUS_XML_ERROR", "DANGEROUS_XML_ERROR"),
                    ("DATASET_EXPIRED", "DATASET_EXPIRED"),
                    ("FILE_TOO_LARGE", "FILE_TOO_LARGE"),
                    ("NESTED_ZIP_FORBIDDEN", "NESTED_ZIP_FORBIDDEN"),
                    ("NO_DATA_FOUND", "NO_DATA_FOUND"),
                    ("SCHEMA_ERROR", "SCHEMA_ERROR"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("XML_SYNTAX_ERROR", "XML_SYNTAX_ERROR"),
                    ("ZIP_TOO_LARGE", "ZIP_TOO_LARGE"),
                ],
                db_index=True,
                help_text="The error code returned for the failed task",
                max_length=50,
                verbose_name="Task Error Code",
            ),
        ),
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILURE", "FAILURE"),
                    ("PENDING", "PENDING"),
                    ("RECEIVED", "RECEIVED"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="task_id",
            field=models.CharField(
                db_index=True,
                help_text="The ID for the Task that was run",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Task ID",
            ),
        ),
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="task_name_failed",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dataqualitytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILURE", "FAILURE"),
                    ("PENDING", "PENDING"),
                    ("RECEIVED", "RECEIVED"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
    ]
