# Generated by Django 2.2.8 on 2019-12-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0011_auto_20191208_2200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DANGEROUS_XML_ERROR", "DANGEROUS_XML_ERROR"),
                    ("DATASET_EXPIRED", "DATASET_EXPIRED"),
                    ("FILE_TOO_LARGE", "FILE_TOO_LARGE"),
                    ("NESTED_ZIP_FORBIDDEN", "NESTED_ZIP_FORBIDDEN"),
                    ("NO_DATA_FOUND", "NO_DATA_FOUND"),
                    ("SCHEMA_ERROR", "SCHEMA_ERROR"),
                    ("SCHEMA_VERSION_MISSING", "SCHEMA_VERSION_MISSING"),
                    ("SCHEMA_VERSION_NOT_SUPPORTED", "SCHEMA_VERSION_NOT_SUPPORTED"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("XML_SYNTAX_ERROR", "XML_SYNTAX_ERROR"),
                    ("ZIP_TOO_LARGE", "ZIP_TOO_LARGE"),
                ],
                db_index=True,
                help_text="The error code returned for the failed task",
                max_length=50,
                verbose_name="Task Error Code",
            ),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="Progress"),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etl_results",
                to="organisation.DatasetRevision",
            ),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="task_name_failed",
            field=models.CharField(
                blank=True,
                help_text="The name of the Celery task which failed",
                max_length=255,
            ),
        ),
    ]
